[workspace]
resolver = "3"
members = ["crates/openshell-client", "crates/sbx"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
repository = "https://github.com/tobiaswadsethdev/sbx"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
