[package]
name = "sbx"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sbx"
path = "src/main.rs"

[dependencies]
openshell-client = { path = "../openshell-client" }
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ratatui = "0.30.2"
tui-term = "0.3"
portable-pty = "0.9"
vt100 = "0.16"
